export const fieldDefinitions = [
  [
    {
      name: "studentId",
      label: "Enter Student I.D / SIN *",
      type: "text",
      optional: false,
      placeholder: "Enter Student ID / SIN Number",
    },
  ],
  //basic details
  [
    {
      name: "firstName",
      label: "First Name*",
      type: "text",
      optional: false,
      placeholder: "Enter First Name",
    },
    {
      name: "surname",
      label: "Surname*",
      type: "text",
      optional: false,
      placeholder: "Enter Surname",
    },
  
    {
      name: "gender",
      label: "Gender*",
      type: "select",
      options: ["Male", "Female"],
      optional: false,
      placeholder: "Select Gender",
    },
    
   
    {
      name: "dept",
      label: "Department*",
      type: "autocomplete",
      options: [
        "OTAT",
        "CT",
        " MLT",
        "CPPCT",
        " OPTO",
        "RIT",
        "MLT",
        "OPTO",
        "ECE",
        "AIDS",
        "CSE",
        "BIO MED",
        "MECH",
        "AGRI",
        "IT",
        "CSE/LE",
        "IT/LE",
        "MECH/LE",
        "M.E CSE",
        "AIDS/LE",
        "CYBER SECURITY",
        "ECE/LE",
        "M.E IS",
        "HI",
        "Nursing",
        "B.Pharm/LE",
        "B.Pharm",
        "D.Pharm",
        "Pharm D",
        "M.Pharm",
        "BIO MED/LE",
        "AGRI/LE",
        "CYBER SECURITY/LE",
      ],
      optional: false,
      placeholder: "Enter Department",
    },
    {
      name: "batch",
      label: "Batch *",
      type: "select",
      options: [
        "2020-2024",
        "2021-2024",
        "2022-2024",
        "2022-2025",
        "2022-2026",
        "2023-2025",
        "2023-2026",
        "2023-2027",
        "2023-2029",
        "2024-2028",
        "2024-2026",
        "2024-2027",
        "2025-2029",
        "2025-2027",
      ],
      optional: false,
      placeholder: "Enter Batch",
    },
    {
      name: "college",
      label: "College*",
      type: "select",
      options: ["AHS", "ENGINEERING", "HEALTH", "Nursing", "PHARMACY"],
      optional: false,
      placeholder: "Select College",
    },


  ],
];

export const initialFatherValues = [
  // { name: 'fatherId', label: 'Father Id', type: 'text', optional: true, placeholder: 'Enter Father ID' },
  {
    name: "fatherFirstName",
    label: "Father's First Name*",
    type: "text",
    optional: false,
    placeholder: "Enter Father's First Name",
  },
  {
    name: "fatherDateOfBirth",
    label: "Father's Date of Birth (DD/MM/YYYY)*",
    type: "date",
    optional: false,
    placeholder: "Enter Father's Date of Birth",
  },
  {
    name: "fatherEmail",
    label: "Father's E-Mail Address",
    type: "text",
    optional: true,
    placeholder: "Enter Father's Email Address",
  },
  {
    name: "fatherPrimaryMobileNo",
    label: "Father's Primary Mobile No*",
    type: "phone",
    optional: false,
    placeholder: "Enter Father's Primary Mobile No",
  },
  {
    name: "fatherSecondaryMobileNo",
    label: "Father's Secondary Mobile No",
    type: "phone",
    optional: true,
    placeholder: "Enter Father's Secondary Mobile No",
  },
  {
    name: "fatherAddressLine1",
    label: "Father's Address Line 1*",
    type: "textarea",
    optional: false,
    placeholder: "Enter Father's Address Line 1",

    sameaslable: "Student Address",
    populate: true,
    sameas: "address",
  },
  {
    name: "fatherArea",
    label: "Father's Area*",
    type: "text",
    optional: false,
    placeholder: "Enter Father's Area",
    sameaslable: "Student Area",
    populate: true,
    sameas: "area",
  },
  {
    name: "fatherTownVillage",
    label: "Father's Town/Village*",
    type: "text",
    optional: false,
    placeholder: "Enter Father's Town/Village",
    sameaslable: "Student Town/Village",
    populate: true,
    sameas: "townVillage",
  },
  {
    name: "fatherPincode",
    label: "Father's Pincode*",
    type: "text",
    optional: false,
    placeholder: "Enter Father's Pincode",
    sameaslable: "Student Pincode",
    populate: true,
    sameas: "pincode",
  },
  {
    name: "fatherProfession",
    label: "Father's Profession*",
    type: "select",
    options: [
      "Private Employee",
      "Public Sector Employee",
      "Businessman",
      "Self-employed",
      "Farmer",
      "Teacher",
      "Doctor",
      "Lawyer",
      "Government Officer",
      "Military Personnel",
      "Daily wages",
      "Retired",
      "Student",
      "Entrepreneur",
    ],
    optional: false,
    placeholder: "Select Profession",
  },
  {
    name: "fatherIncome",
    label: "Father's Income*",
    type: "select",
    options: ["<2.5L", "2.5L to 5L", "5L to 10L", ">10L"],
    optional: false,
    placeholder: "Select Income Range",
  },
];

export const initialMotherValues = [
  // { name: 'motherId', label: 'Mother Id', type: 'text', optional: true, placeholder: 'Enter Mother ID' },
  {
    name: "motherFirstName",
    label: "Mother's First Name*",
    type: "text",
    optional: false,
    placeholder: "Enter Mother's First Name",
  },
  {
    name: "motherDateOfBirth",
    label: "Mother's Date of Birth (DD/MM/YYYY)*",
    type: "date",
    optional: false,
    placeholder: "Enter Mother's Date of Birth",
  },
  {
    name: "motherEmail",
    label: "Mother's E-Mail Address",
    type: "text",
    optional: true,
    placeholder: "Enter Mother's Email Address",
  },
  {
    name: "motherPrimaryMobileNo",
    label: "Mother's Primary Mobile No*",
    type: "phone",
    optional: false,
    placeholder: "Enter Mother's Primary Mobile No",
  },
  {
    name: "motherSecondaryMobileNo",
    label: "Mother's Secondary Mobile No",
    type: "phone",
    optional: true,
    placeholder: "Enter Mother's Secondary Mobile No",
  },
  {
    name: "motherAddressLine1",
    label: "Mother's Address Line 1*",
    type: "textarea",
    optional: false,
    placeholder: "Enter Mother's Address Line 1",
    sameaslable: "Student Address",
    populate: true,
    sameas: "address",
  },
  {
    name: "motherArea",
    label: "Mother's Area*",
    type: "text",
    optional: false,
    placeholder: "Enter Mother's Area",
    sameaslable: "Student Area",
    populate: true,
    sameas: "area",
  },
  {
    name: "motherTownVillage",
    label: "Mother's Town/Village*",
    type: "text",
    optional: false,
    placeholder: "Enter Mother's Town/Village",
    sameaslable: "Student Town/Village",
    populate: true,
    sameas: "townVillage",
  },
  {
    name: "motherPincode",
    label: "Mother's Pincode*",
    type: "text",
    optional: false,
    placeholder: "Enter Mother's Pincode",
    sameaslable: "Student Pincode",
    populate: true,
    sameas: "pincode",
  },
  {
    name: "motherProfession",
    label: "Mother's Profession*",
    type: "select",
    options: [
      "Housewife",
      "Private Employee",
      "Public Sector Employee",
      "Businessman",
      "Self-employed",
      "Farmer",
      "Teacher",
      "Doctor",
      "Lawyer",
      "Government Officer",
      "Military Personnel",
      "Daily wages",
      "Retired",
      "Student",
      "Entrepreneur",
    ],
    optional: false,
    placeholder: "Select Profession",
  },
  {
    name: "motherIncome",
    label: "Mother's Income*",
    type: "select",
    options: ["<2.5L", "2.5L to 5L", "5L to 10L", ">10L"],
    optional: false,
    placeholder: "Enter Mother's Income",
  },
];

export const initialGuardianValues = [
  // { name: 'guardianId', label: 'Guardian Id', type: 'text', optional: true, placeholder: 'Enter Guardian ID' },
  {
    name: "guardianFirstName",
    label: "Guardian's First Name*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's First Name",
  },
  {
    name: "guardianGender",
    label: "Guardian's Gender*",
    type: "select",
    options: ["Male", "Female", "Other"],
    optional: false,
    placeholder: "Select Gender",
  },
  {
    name: "guardianDateOfBirth",
    label: "Guardian's Date of Birth (DD/MM/YYYY)*",
    type: "date",
    optional: false,
    placeholder: "Enter Guardian's Date of Birth",
  },
  {
    name: "guardianEmail",
    label: "Guardian's E-Mail Address",
    type: "text",
    optional: true,
    placeholder: "Enter Guardian's Email Address",
  },
  {
    name: "guardianPrimaryMobileNo",
    label: "Guardian's Primary Mobile No*",
    type: "phone",
    optional: false,
    placeholder: "Enter Guardian's Primary Mobile No",
  },
  {
    name: "guardianSecondaryMobileNo",
    label: "Guardian's Secondary Mobile No",
    type: "phone",
    optional: true,
    placeholder: "Enter Guardian's Secondary Mobile No",
  },
  {
    name: "guardianAddressLine1",
    label: "Guardian's Address Line 1*",
    type: "textarea",
    optional: false,
    placeholder: "Enter Guardian's Address Line 1",
  },
  {
    name: "guardianArea",
    label: "Guardian's Area*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's Area",
  },
  {
    name: "guardianTownVillage",
    label: "Guardian's Town/Village*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's Town/Village",
  },
  {
    name: "guardianPincode",
    label: "Guardian's Pincode*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's Pincode",
  },
  {
    name: "guardianRelationWithStudent",
    label: "Guardian's Relation with Student*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's Relation with Student",
  },
  {
    name: "guardianProfession",
    label: "Guardian's Profession*",
    type: "select",
    options: [
      "Private Employee",
      "Public Sector Employee",
      "Businessman",
      "Self-employed",
      "Farmer",
      "Teacher",
      "Doctor",
      "Lawyer",
      "Daily wages",
      "Government Officer",
      "Military Personnel",
      "Housewife",
      "Retired",
      "Student",
      "Entrepreneur",
    ],
    optional: false,
    placeholder: "Select Profession",
  },
  {
    name: "guardianIncome",
    label: "Guardian's Income*",
    type: "select",
    options: ["<2.5L", "2.5L to 5L", "5L to 10L", ">10L"],
    optional: false,
    placeholder: "Enter Guardian's Income",
  },
];

export const stepNames = [
  "Validate before Adding SIN",
  "Enter Basic Details",
  
];
