export const fieldDefinitions = [
  [
    {
      name: "studentId",
      label: "Enter Student I.D / SIN *",
      type: "text",
      optional: false,
      placeholder: "Enter Student ID / SIN Number",
    },
  ],
  //basic details
  [
    {
      name: "firstName",
      label: "First Name*",
      type: "text",
      optional: false,
      placeholder: "Enter First Name",
    },
    {
      name: "surname",
      label: "Surname*",
      type: "text",
      optional: false,
      placeholder: "Enter Surname",
    },
    {
      name: "fullname",
      label: "Full Name ( As per Aadhar)*",
      type: "text",
      optional: false,
      placeholder: "Enter Full name as per Aadhar",
    },
    {
      name: "gender",
      label: "Gender*",
      type: "select",
      options: ["Male", "Female"],
      optional: false,
      placeholder: "Select Gender",
    },
    {
      name: "dateOfBirth",
      label: "Date of Birth*",
      type: "date",
      optional: false,
      placeholder: "Select Date of Birth",
    },
    {
      name: "bloodGroup",
      label: "Blood Group*",
      type: "select",
      options: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
      optional: false,
      placeholder: "Select Blood Group",
    },

    // { name: 'userId', label: 'User ID', type: 'text', optional: true, placeholder: 'Enter User ID' },
    {
      name: "email",
      label: "E-Mail Address*",
      type: "email",
      optional: false,
      placeholder: "Enter Email Address",
    },
    {
      name: "mobileNumber",
      label: "Mobile Number*",
      type: "phone",
      optional: false,
      placeholder: "Enter Mobile Number",
    },
    {
      name: "whatsappNumber",
      label: "Whatsapp Number*",
      type: "phone",
      optional: true,
      placeholder: "Enter Whatsapp Number",
      sameaslable: "Mobile Number",
      populate: true,
      sameas: "mobileNumber",
    },
    {
      name: "address",
      label: "Address*",
      type: "textarea",
      optional: false,
      placeholder: "Enter Address",
    },
    {
      name: "area",
      label: "Street/Area*",
      type: "text",
      optional: false,
      placeholder: "Enter Area",
    },

    {
      name: "talukaCity",
      label: "Taluka City*",
      type: "text",
      optional: false,
      placeholder: "Enter Taluka City",
    },
    {
      name: "townVillage",
      label: "Town Village*",
      type: "text",
      optional: false,
      placeholder: "Enter Town Village",
    },
    {
      name: "district",
      label: "District*",
      type: "autocomplete",
      options: [
        // Tamil Nadu
        "Chennai",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Kanchipuram",
        "Kanyakumari",
        "Karur",
        "Madurai",
        "Nagapattinam",
        "Namakkal",
        "Nilgiris",
        "Perambalur",
        "Pudukkottai",
        "Ramanathapuram",
        "Salem",
        "Sivaganga",
        "Tenkasi",
        "Thanjavur",
        "The Nilgiris",
        "Thoothukudi",
        "Tiruchirappalli",
        "Tirunelveli",
        "Tiruppur",
        "Tiruvallur",
        "Tiruvannamalai",
        "Vellore",
        "Villupuram",
        "Virudhunagar",

        // Karnataka
        "Bagalkote",
        "Ballari",
        "Belagavi",
        "Bellary",
        "Bengaluru Rural",
        "Bengaluru Urban",
        "Bidar",
        "Chamarajanagar",
        "Chikkaballapur",
        "Chikmagalur",
        "Chitradurga",
        "Dakshina Kannada",
        "Davangere",
        "Dharwad",
        "Gadag",
        "Hassan",
        "Haveri",
        "Kalaburagi",
        "Kodagu",
        "Kolar",
        "Koppal",
        "Mandya",
        "Mysuru",
        "Raichur",
        "Ramanagara",
        "Shimoga",
        "Tumkur",
        "Udupi",
        "Uttara Kannada",
        "Yadgir",

        // Kerala
        "Alappuzha",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Malappuram",
        "Palakkad",
        "Pathanamthitta",
        "Thrissur",
        "Wayanad",

        // Andhra Pradesh
        "Anantapur",
        "Chittoor",
        "East Godavari",
        "Guntur",
        "Krishna",
        "Kurnool",
        "Nellore",
        "Prakasam",
        "Srikakulam",
        "Visakhapatnam",
        "Vizianagaram",
        "West Godavari",
        "YSR Kadapa",
      ],
      optional: false,
      placeholder: "Enter District",
    },
    {
      name: "state",
      label: "State*",
      type: "select",
      options: [
        "Tamil Nadu",
        "Andhra Pradesh",
        "Karnataka",
        "Kerala",
        "Arunachal Pradesh",
        "Assam",
        "Bihar",
        "Chhattisgarh",
        "Goa",
        "Gujarat",
        "Haryana",
        "Himachal Pradesh",
        "Jharkhand",

        "Madhya Pradesh",
        "Maharashtra",
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Nagaland",
        "Odisha",
        "Punjab",
        "Rajasthan",
        "Sikkim",

        "Telangana",
        "Tripura",
        "Uttar Pradesh",
        "Uttarakhand",
        "West Bengal",
        "Andaman and Nicobar Islands",
        "Chandigarh",
        "Dadra and Nagar Haveli and Daman and Diu",
        "Lakshadweep",
        "Delhi",
        "Puducherry",
        "Ladakh",
        "Jammu and Kashmir",
      ],
      optional: false,
      placeholder: "Enter State",
    },

    {
      name: "pincode",
      label: "Pincode*",
      type: "text",
      optional: false,
      placeholder: "Enter Pincode",
    },
    {
      name: "religion",
      label: "Religion*",
      type: "select",
      options: [
        "Hinduism",
        "Islam",
        "Christianity",
        "Sikhism",
        "Buddhism",
        "Jainism",
        "Zoroastrianism",
        "Judaism",
        "Baháʼí Faith",
        "Shinto",
        "Taoism",
        "Confucianism",
        "Shamanism",
        "Animism",
        "Traditional African Religions",
        "Other",
      ],
      optional: false,
      placeholder: "Enter Religion",
    },
    {
      name: "community",
      label: "Community*",
      type: "select",
      options: ["SC", "MBC", "BC", "ST", "SCA", "OC", "BCM", "DNC"],
      optional: false,
      placeholder: "Enter Community",
    },
    {
      name: "dept",
      label: "Department*",
      type: "autocomplete",
      options: [
        "OTAT",
        "CT",
        " MLT",
        "CPPCT",
        " OPTO",
        "RIT",
        "MLT",
        "OPTO",
        "ECE",
        "AIDS",
        "CSE",
        "BIO MED",
        "MECH",
        "AGRI",
        "IT",
        "CSE/LE",
        "IT/LE",
        "MECH/LE",
        "M.E CSE",
        "AIDS/LE",
        "CYBER SECURITY",
        "ECE/LE",
        "M.E IS",
        "HI",
        "Nursing",
        "B.Pharm/LE",
        "B.Pharm",
        "D.Pharm",
        "Pharm D",
        "M.Pharm",
        "BIO MED/LE",
        "AGRI/LE",
        "CYBER SECURITY/LE",
      ],
      optional: false,
      placeholder: "Enter Department",
    },
    {
      name: "batch",
      label: "Batch *",
      type: "select",
      options: [
        "2020-2024",
        "2021-2024",
        "2022-2024",
        "2022-2025",
        "2022-2026",
        "2023-2025",
        "2023-2026",
        "2023-2027",
        "2023-2029",
        "2024-2028",
        "2024-2026",
        "2024-2027",
      ],
      optional: false,
      placeholder: "Enter Batch",
    },
    {
      name: "college",
      label: "College*",
      type: "select",
      options: ["AHS", "ENGINEERING", "HEALTH", "Nursing", "PHARMACY"],
      optional: false,
      placeholder: "Select College",
    },

    {
      name: "75sch",
      label: "7.5 SCH",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
    },

    {
      name: "fg",
      label: "FG ( First Graduate)",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
    },

    {
      name: "postMatric",
      label: "Post Matric",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
    },
  ],

  //father mother guardian details
  [],

  [
    {
      name: "schoolType",
      label: "School Type *",
      type: "select",
      options: [
        "Government School",
        "Government-Aided School",
        "Model School",
        "Private School",
        "Matriculation School",
        "International General Certificate of Secondary Education (IGCSE)",
        "Central Board of Secondary Education (CBSE)",
        "Indian Certificate of Secondary Education (ICSE)",
      ],
      optional: false,
      placeholder: "Select School Type",
    },
    ////////////// add dropdwon for name
    {
      name: "schoolName",
      label: "School Name (12th) *",
      type: "autocomplete",
      options: [
        "GOVT GIRLS HR SEC SCHOOL T N PALAYAM ERODE",
        "SRI PARIYUR AMMAN HR SEC SCHOOL T N PALAYAM GOBICHETTIPALAYAM",
        "GOVT HR SEC SCHOOL BUNGALOWPUDUR",
        "GOVT HR SEC SCHOOL ,KONGARPALAYAM",
        "KAMARAJ HR SEC SCHOOL NAMBIYUR",
        "GOVT HR SEC SCHOOL VEMANDAMPALAYAM ERODE",
        "GOVERNMENT BOYS HR SEC SCHOOL NAMBIYUR",
        "GOVERNMENT HIGHER SECONDARY SCHOOL, KOODAKKARAI.",
        "GOVT HR SEC SCHOOL KASIPALAYAM GOBI TK",
        "GOVERNMENT HR.SEC.SCHOOL, POLAVAKALIPALAYAM",
        "S M GOVT HIGHER SECONDARY SCHOOL ODATHURAI",
        "GOVT HR SEC SCHOOL KALLIPATTI",
        "SHANGUINE MATRICULATION HIGHER SECONDARY SCHOOL, KURUMANDUR",
        "GOVT HR SEC SCHOOL KURUMANDUR",
        "GOVT MODEL HR SEC SCHOOL GETTICHEVIYUR",
        "MUNICIPAL BOYS HIGHER SECONDARY SCHOOL, GOBICHETTIPALAYAM",
        "DIAMOND JUBILEE  HIGHER SECONDARY  SCHOOL, GOBICHETTIPALAYAM",
        "GOVT HR SEC SCHOOL KARATTADIPALAYAM",
        "CKK MATRIC GIRLS HR SEC SCHOOL GOBICHETTIPALAYAM ERODE",
        "PALANIAMMAL GIRLS HR SEC SCHOOL GOBICHETTIPALAYAM",
        "KOMARASAMY GOUNDER MATRIC HR SEC SCHOOL, KURUMANDUR ERODE",
        "SHREE GURUKULAM HR SEC SCHOOL MOOLAVAIKKAL",
        "S V V HR SEC SCHOOL THASAMPALAYAM GOBI ERODE",
        "KAMBAN KALVI NILAYAM MATRIC. HS SCHOOL, GOBI",
        "GANDHI KALVI NILAYAM HIGHER SECONDARY SCHOOL,KUGALUR",
        "MODEL HR SEC SCHOOL NAMBIYUR",
        "KUMUTHA MATRIC HR SEC SCHOOL NAMBIYUR",
        "GOVERNMENT HR SEC SCHOOL SAVAKKATTUPALAYAM",
        "GOVERNMENT HR SEC SCHOOL VELLANKOIL",
        "GOVERNMENT GIRLS HR SEC SCHOOL NAMBIYUR",
        "BHARATHI VIDHYALAYA MATRIC HR SEC SCHOOL GOBICHETTIPALAYAM",
        "ST PAULS MATRIC HIGHER SECONDARY SCHOOL,  PATHY",
        "MUNICIPAL GIRLS HR SEC SCHOOL, GOBICHETTIPALAYAM",
        "GOVT HR SEC SCHOOL MALAYAPPALAYAM",
        "AMALA MATRIC HR SEC SCHOOL, GOBICHETTIPALAYAM",
        "SHREE VIDYALAYA MATRIC HS SCHOOL, GOBI",
        "GOVERNMENT HIGHER SECONDARY SCHOOL ELUR ERODE",
        "GOVERNMENT HR SEC SCHOOL DASAPPAGOUNDENPUDUR",
        "GOVT BOYS HR SEC SCHOOL MODAKKURICHI",
        "GOVT GIRLS HR SEC SCHOOL MODAKKURICHI ERODE",
        "GOVT HR SEC SCHOOL ELUMATHUR ERODE",
        "SRI SANKARA VID MATRIC HR SEC SCHOOL SIVAGIRI ERODE",
        "GOVERNMENT HIGHER SECONDARY SCHOOL, THANDAMPALAYAM",
        "GOVT BOYS HR SEC SCHOOL SIVAGIRI 638109",
        "SREE AMMAN MATRICULATION HSS,EVK SAMPATH NAGAR, ERODE-11",
        "GOVT HR SEC SCHOOL VEERAPPANCHATRAM ERODE",
        "GOVT  MODEL HR SEC SCHOOL ERODE",
        "GOVERNMENT HIGHER SECONDARY SCHOOL B P AGRAHARAM",
        "GOVERNMENT HIGHER SECONDARY SCHOOL NANJAPPAGOUNDAN VALASU ERODE",
        "GOVERNMENT HIGHER SECONDARY SCHOOL RAMANATHAPURAMPUDUR ERODE",
        "RAJENDRAN MATRIC HR SEC SCHOOL VADUGAPATTI",
        "GOVERNMENT HR SEC SCHOOL ARACHALUR",
        "LIONS MATRIC HR SEC SCHOOL PALANIGOUNDANVALASU",
        "ISHA VIDHYA MATRICULATION HIGHER SECONDARY SCHOOL,PERUMAPALAYAM",
        "GOVT HR SEC SCHOOL AVALPOONDURAI ERODE",
        "SWAMI MATRIC HR SEC SCHOOL MODAKKURICHI",
        "P K P SWAMY MATRIC HSS,KALYANIPURAM",
        "KONGU MATRIC HR SEC SCHOOL KARUMANDAMPALAYAM",
        "GOVERNMENT HR SEC SCHOOL GANAPATHIPALAYAM",
        "GOVT HR SEC SCHOOL PASUR",
        "GOVERNMENT HR SEC SCHOOL VELLOTTAMPARAPPU ERODE 638154",
        "M R G GOVERNMENT GIRLS HR SEC SCHOOL , VEERAPPANCHATRAM, ERODE - 638004.",
        "NANDHI MATRIC HR SEC SCHOOL THIRUNAGAR COLONY ERODE",
        "SRI SARASWATHI VIDHYALAYA Mat.HSS,MAYAPURAM, ERODE",
        "KAMARAJ MUNICIPAL BOYS HR SEC SCHOOL KARUNGALPALAYAM ERODE",
        "SIDDHARTHA MATRIC HR SEC SCHOOL ERODE",
        "AL - AMEEN MATRICULATION HSS, CAUVERY ROAD",
        "MUNICIPAL GIRLS HR SEC SCHOOL KARUNGALPALAYAM ERODE-638 003",
        "RAILWAY COLONY MPL HR SEC SCHOOL KOLLAMPALAYAM ERODE",
        "BHARATHI KALVI NILAYAM HR SEC SCHOOL NASIYANUR",
        "M S SENGUNTHAR HR SEC SCHOOL RANGAMPALAYAM",
        "C S I BOYS HR SEC SCHOOL ERODE",
        "C S I GIRLS HR SEC SCHOOL ERODE",
        "GOVERNMENT HR SEC SCHOOL UNJALUR",
        "S S V HR SEC SCHOOL KODUMUDI",
        "GOVT HR SEC SCHOOL SALAIPUDUR",
        "V V C R M SENGUNTHAR GIRLS HR SEC SCHOOL ERODE",
        "THE SENGUNTHAR HR SEC SCHOOL ERODE",
        "ARULNERI THIRUPPANI MANDRAM HR SEC SCHOOL, ERODE",
        "KONGU NATIONAL MATRIC HR SEC SCHOOL NANJANAPURAM",
        "A.E.T.MATRICULATION HSS, KATHIRAMPATTI",
        "NIRMALA MATHA CONVENT MATRIC HR SEC SCHOOL ERODE",
        "BHARATHI VIDYA BHAVAN MATRIC HR SEC SCHOOL THINDAL ERODE - 12",
        "GOVERNMENT HR SEC SCHOOL THINDAL",
        "SHRI JANANI MATRICULATION HIGHER SECONDARY SCHOOL, ELLAPALAYAM",
        "ERODE HINDU KALVI NILAYAM MATRIC HR SEC SCHOOL MAMARATHUPALAYAM ERODE",
        "SRI SATHYA SAI MATRIC HR SEC SCHOOL V THAYIR PALAYAM CHITHODE",
        "JAYCEES MATRIC HIGHER SECONDARY SCHOOL",
        "KONGU KALVI NILAYAM MATRIC HR SEC SCHOOL RANGAMPALAYAM",
        "SRI SAKTHI VIDHYA NIKETHAN MATRIC HSS,RANGAMPALAYAM",
        "GREENPARK MATRIC HR SEC SCHOOL,KG PALAYAM,ERODE",
        "GOVT HR SEC SCHOOL KASIPALAYAM ERODE- 9",
        "NAVARASAM MATRIC HR SEC SCHOOL PALLIYUTHU",
        "GOVT HR SEC SCHOOL MUGASI ANUMANPALLI",
        "S V N MATRIC HR SEC SCHOOL KONGAMPALAYAM ERODE",
        "GOVT HR SEC SCHOOL RAYAPALAYAM CHITTODE ERODE",
        "THAMARAI MATRIC HR SEC SCHOOL, THAMARAIPALAYAM",
        "GOVT HR SEC SCHOOL THAMARAIPALAYAM",
        "URC PALANIAMMAL MATRIC HR SEC SCHOOL ERODE",
        "AL - AMEEN MATRICULATION HSS, VILLARASAMPATTI ERODE",
        "VELLALAR GIRLS MATRIC HR SEC SCHOOL  THINDAL  ERODE - 12",
        "CHRISTHU JYOTHI MATRIC HR SEC SCHOOL  B P AGRAHARAM ERODE",
        "KALAIMAGAL KALVI NILAYAM GIRLS HR SEC SCHOOL ERODE",
        "CARMEL MATRIC HR SEC SCHOOL ERODE",
        "ASHRAM MATRICULATION HSS, KOLLAMPALAYAM, ERODE",
        "GOVT HR SEC SCHOOL, LAKKAPURAM",
        "GOVERNMENT GIRLS HR SEC SCHOOL CHITHODE",
        "GOVERNMENT HIGHER SECONDARY SCHOOL, KUMALANKUTTAI",
        "GOVT HR SEC SCHOOL. P. METTUPALAYAM ERODE.",
        "GOVERNMENT MODEL HR SEC SCHOOL KAVINDAPADI",
        "GOVT GIRLS HR SEC SCHOOL ANTHIYUR",
        "GOVT HR SEC SCHOOL OLAGADAM",
        "ST.MARYS MATRIC HR. SEC.SCHOOL  KURUPPANAICKENPALAYAM",
        "GOVT BOYS HR SEC SCHOOL BHAVANI ERODE",
        "GOVT VINOBHA HR SEC SCHOOL THALAVAIPETTAI ERODE",
        "ST MICHAELS HIGHER SECONDARY SCHOOL MICHAELPALAYAM",
        "GOVT BOYS HR SEC SCHOOL ANTHIYUR ERODE",
        "GOVT GIRLS HR SEC SCHOOL KAVINDAPADI ERODE",
        "GOVT HR SEC SCHOOL AYYAMPALAYAM ERODE 638 455",
        "SARASWATHI VIDHYASHRAM MATRIC HR SEC SCHOOL KAVINDAPADI",
        "TNK MATRIC HR SEC SCHOOL SALANGAPALAYAM ERODE",
        "GOVT GIRLS HR SEC SCHOOL BHAVANI",
        "S E T HR SEC SCHOOL POONACHI ERODE",
        "KALAIVANI KALVI NILAYAM MATRICULATION HIGHER SECONDARY SCHOOL,CHENNAMPATTI.",
        "GOVT HR SEC SCHOOL CHENNAMPATTI ERODE DISTRICT",
        "M A M EXEL MATRIC HR SEC SCHOOL GURUVAREDDIYUR",
        "GOVERNMENT HR SEC SCHOOL, GURUVAREDDIYUR",
        "MODEL HR SEC SCHOOL MATHUR ERODE DISTRICT",
        "GOVT HR SEC SCHOOL VELLITHIRUPPUR",
        "MODEL HR SEC SCHOOL ANTHIYUR",
        "GOVT HR SEC SCHOOL ALAMPALAYAM",
        "SRI SAKTHI SUPREME IDEAL VIKAS MATRIC HIGHER SECONDARY SCHOOL SANKARAGOUNDANPALAYAM",
        "GOVERNMENT HR SEC SCHOOL MYLAMBADI",
        "ST.IGNATIUS HR SEC SCHOOL  BUDAPADI,ERODE",
        "GOVT HR SEC SCHOOL SINGAMPETTAI ERODE",
        "GOVT TRIBAL RESIDENTIAL HR SEC SCHOOL , BARGUR -  ERODE",
        "SAKTHI HR SEC SCHOOL NACHIMUTHUPURAM SAKTHINAGAR",
        "GOVT HR SEC SCHOOL MOONGILPATTI ERODE",
        "MANGALAM HSS ANTHIYUR",
        "SREE SARAVANA NIKETAN MATRIC HR SEC SCHOOL, NERINJIPETTAI",
        "GOVT HR SEC SCHOOL NERINJIPETTAI ERODE",
        "VISHWESVARAIYAH MATRIC HR SEC SCHOOL THOPPUR ANTHIYUR",
        "GOVT HR SEC SCHOOL ATHANI",
        "GOVT HR SEC SCHOOL A SEMBULICHAMPALAYAM",
        "GOVT HR SEC SCHOOL A PUDUPALAYAM",
        "VIVEGAM VIDHYA BHAVAN MATRIC HIGHER SECONDARY SCHOOL,VEMPATHI",
        "GHSS  DEVARMALAI",
        "GOVERNMENT HIGHER SECONDARY SCHOOL OOSUR",
        "ROOTS MATRIC HIGHER  SECONDARY SCHOOL, MOONGIL PALAYAM",
        "GOVERNMENT BOYS HR SEC SCHOOL PERUNDURAI",
        "SAKTHI HSS, SAKTHIPURAM, CHITHODE POST",
        "SHREE SWAMI VIVEKANANDHA MATRIC HR SEC SCHOOL PERUNDURAI",
        "GOVT GIRLS HR SEC SCHOOL, PERUNDURAI",
        "GOVT HR SEC SCHOOL KANJIKOVIL ERODE",
        "KONGU V K N MATRIC HR SEC SCHOOL KANJIKOVIL",
        "GOVT HR SEC SCHOOL NALLAMPATTI",
        "GOVT HR SEC SCHOOL VELLODE",
        "VIVEKANANTHA MATRIC HR SEC SCHOOL V VELLODE",
        "M P D GOVT HR SEC SCHOOL THINGALUR",
        "YOUNG INDIA MATRIC HSS,VEPPILI PIRIVU",
        "VIMALA MATRIC HR SEC SCHOOL THOPPUPALAYAM CHENNIMALAI",
        "KOMARAPPA SENGUNTHAR HR SEC SCHOOL",
        "SHRI GANGA HIGHER SECONDARY SCHOOL INGUR",
        "GOVT HR SEC SCHOOL INGUR ERODE",
        "BHARATHI MATRIC HIGHER SECONDARY SCHOOL,SHANMUGAPURAM, VIJAYAMANGALAM",
        "KONGU VELLALAR MATRIC HR SEC SCHOOL CHENNIMALAI ERODE",
        "GOVERNMENT HR SEC SCHOOL PASUVAPATTI",
        "GOVERNMENT HR SEC SCHOOL THIPPAMPALAYAM",
        "KONGU VELLALAR MATRIC HR SEC SCHOOL PERUNDURAI",
        "KARUNYA VIDYA BHAVAN MATRIC HIGHER SECONDARY SCHOOL,PERUNDURAI",
        "GREEN GARDEN MATRIC HR SEC SCHOOL KORAKKATTUVALASU ERODE",
        "SHRI RAJALAKSHMI MATRICULATION HIGHER SECONDARY SCHOOL KARATTUPALAYAM",
        "GOVT MODEL HR SEC SCHOOL SEENAPURAM",
        "GOVT HR SEC SCHOOL THUDUPATHY",
        "THE RICHMOND MATRICULATION HIGHER SECONDARY SCHOOL, SEENAPURAM",
        "GOVT HR SEC SCHOOL VIJAYAMANGALAM",
        "VIJAY VIKAS MATRIC HR SEC SCHOOL KAMPULIYAMPATTY",
        "DON BOSCO MATRICULATION HIGHER SECONDARY SCHOOL, THALAVADI",
        "GHSS THALAVADI",
        "ST. JOSEPHS HIGHER SECONDARY SCHOOL, SOOSAIPURAM, ERODE",
        "GOVT GIRLS MODEL HR SEC SCHOOL SATHYAMANGALAM ERODE DISTRICT",
        "SRT UNIVERSAL MATRIC HR SEC SCHOOL SATHYAMANGALAM",
        "GOVT HR SEC SCHOOL PANAKAHALLI",
        "GOVT HR SEC SCHOOL PASUVANAPURAM",
        "GHSS KOTTAMALAM",
        "GOVERNMENT HR SEC SCHOOL DODDAMPALAYAM",
        "SOUNDRAM VIDYALAYA MATRIC HR SEC SCHOOL  RAJAN NAGAR",
        "GOVERNMENT  HIGHER  SECONDARY  SCHOOL, BHAVANI SAGAR",
        "GOVERNMENT HIGHER SECONDARY SCHOOL KALKADAMBUR",
        "SARU MATRICULATION HIGHER SECONDARY SCHOOL",
        "THE NEST SCHOOL MATRIC HIGHER SECONDARY SCHOOL PUDUVADAVALLI",
        "GOVT BOYS HR SEC SCHOOL SATHYAMANGALAM",
        "AMMA MATRICULATION HIGHER SECONDARY SCHOOL, PUNJAI PULIAMPATTI",
        "MAMAHARISHI EASWARAYA GURUKULAM MATRICULATION HR.SEC.SCHOOL, THABOVANAM",
        "S R C MEMORIAL MATRIC HIGHER SECONDARY SCHOOL PUNJAI PULIAMPATTI",
        "KOM GOVT GIRLS HR SEC SCHOOL P PULIYAMPATTI",
        "GOVERNMENT HR SEC SCHOOL PANAYAMPALLI",
        "GOVT HR SEC SCHOOL KAVILIPALAYAM",
        "KVK GOVT BOYS HR SEC SCHOOL P PULIYAMPATTI",
        "GTRHSS HASANUR",
        "SRI RAGAVENDRA MATRICULATION HIGHER SECONDARY SCHOOL  SATHYAMANGALAM",
        "SNR VIDHYA NETHRA MATRICULATION HR.SEC.SCHOOL,VINNAPPALLI",
        "SRI RAGAVENDRA HR SEC. SCHOOL, SATHYAMANGALAM",
        "B SUNDARAM CHETTIYAR GOVT HR SEC SCHOOL KEMBANAICKENPALAYAM",
        "BAVN MATRIC HR SEC SCHOOL SATHYAMANGALAM",
        "LITTLE FLOWER MATRIC HR SEC SCHOOL SATHYAMANGALAM",
        "GOVT MODEL HR SEC SCHOOL , SATHYAMANGALAM",
        "ST. JAMES MATRIC HR SEC SCHOOL  SATHYAMANGALAM",
        "ST. FRANCIS XAVIER HR SEC SCHOOL, PERIYA KODIVERY",
        "GOVT MODEL HR SEC SCHOOL MALLANGULI, THALAVADI",
        "GOVERNMENT HR SEC SCHOOL KADATHUR ERODE(DT)",
        "SHREE VALLI MATRIC HSS ICHIPPALAYAM",
        "GOVT GIRLS HR SEC SCHOOL SIVAGIRI 638109",
        "GOVERNMENT HR SEC SCHOOL MINNAPPALAYAM",
        "ADHARSH VIDHYALAYA MATRIC HR SEC SCHOOL PARUVACHI ERODE",
        "SARATHA MATRIC HR SEC SCHOOL MODACHUR GOBI",
        "MRS MATRIC HIGHER SECONDARY SCHOOL, KOLAPPALUR",
        "MUNICIPAL HR SEC SCHOOL MODACHUR GOBICHETTIPALAYAM",
        "MOTHERS MATRIC HIGHER SECONDARY SCHOOL., KALINGARAYANPALAYAM",
        "GRACE MATRIC HR SEC SCHOOL ELAVAMALAI ERODE DISTRICT",
        "GOVT HR SEC SCHOOL PERIYAPULIYUR ERODE",
        "ERODE DISTRICT GOVERNMENT MODEL SCHOOL",
      ],
      optional: false,
      placeholder: "Enter School Name (12th) *",
    },

    {
      name: "medium",
      label: "Medium",
      type: "select",
      options: [
        "English",
        "Hindi",
        "Bengali",
        "Telugu",
        "Marathi",
        "Tamil",
        "Urdu",
        "Gujarati",
        "Malayalam",
        "Kannada",
        "Odia",
        "Punjabi",
        "Assamese",
        "Maithili",
        "Santali",
        "Konkani",
        "Sindhi",
        "Kashmiri",
        "Nepali",
        "Manipuri",
        "Bodo",
        "Sanskrit",
      ],
      optional: true,
      placeholder: "Select Medium",
    },

    {
      name: "tenthMark",
      label: "10th Mark % *",
      type: "text",
      optional: false,
      placeholder: "Enter 10th Mark",
    },
    {
      name: "tenthpassoutyear",
      label: "10th Year of Passing",
      type: "text",
      optional: false,
      placeholder: "Enter 10th Pass out Year",
    },
    {
      name: "twelfthMarkPercent",
      label: "12th Mark % *",
      type: "text",
      optional: false,
      placeholder: "Enter 12th Mark %",
    },
    {
      name: "twelethpassoutyear",
      label: "12th Year of Passing",
      type: "text",
      optional: false,
      placeholder: "Enter 12th Pass out Year",
    },
    {
      name: "twelfthMathsMarkOutOf100",
      label: "12th Maths Mark (out of 100) *",
      type: "text",
      optional: false,
      placeholder: "Enter 12th Maths Mark (out of 100)",
    },
    {
      name: "twelfthPhysicsMarkOutOf100",
      label: "12th Physics Mark (out of 100) *",
      type: "text",
      optional: false,
      placeholder: "Enter 12th Physics Mark (out of 100)",
    },
    {
      name: "twelfthChemistryMarkOutOf100",
      label: "12th Chemistry Mark (out of 100) *",
      type: "text",
      optional: false,
      placeholder: "Enter 12th Chemistry Mark (out of 100)",
    },
    {
      name: "twelfthBilologyMarkOutOf100",
      label: "12th Bilology Mark (out of 100) ",
      type: "text",
      optional: true,
      placeholder: "Enter 12th Bilology Mark (out of 100)",
    },
    {
      name: "twelfthBotanyMarkOutOf100",
      label: "12th Botany Mark (out of 100)",
      type: "text",
      optional: true,
      placeholder: "Enter 12th Botany Mark (out of 100)",
    },
    {
      name: "twelfthZoologyMarkOutOf100",
      label: "12th Zoology Mark (out of 100)",
      type: "text",
      optional: true,
      placeholder: "Enter 12th Zoology Mark (out of 100)",
    },
    {
      name: "twelfthCompScienceMarkOutOf100",
      label: "12th Comp Science Mark (out of 100)",
      type: "text",
      optional: true,
      placeholder: "Enter 12th Comp Science Mark (out of 100)",
    },
  ],

  // Identity
  [
    {
      name: "aadharNo",
      label: "Aadhar No *",
      type: "text",
      optional: false,
      placeholder: "Enter Aadhar No",
    },
    {
      name: "panCard",
      label: "PanCard No",
      type: "text",
      optional: true,
      placeholder: "Enter Pancard No",
    },
    {
      name: "passportNumber",
      label: "Passport Number",
      type: "text",
      optional: true,
      placeholder: "Enter Passport No",
    },
    {
      name: "drivinglicense",
      label: "Do you have a driving license?",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
      placeholder: "Do you have a driving license?",
    },
    {
      name: "emisNo",
      label: "EMIS No",
      type: "text",
      optional: true,
      placeholder: "Enter EMIS No",
    },

    {
      name: "bankDetails",
      label: "Bank Details (Aadhar Linked)",
      type: "textarea",
      optional: true,
      placeholder: "Enter Bank Details (Aadhar Linked)",
    },
    {
      name: "languagesKnown",
      label: "Languages Known",
      type: "selectmulti",
      options: [
        "Hindi",
        "Bengali",
        "Telugu",
        "Marathi",
        "Tamil",
        "Urdu",
        "Gujarati",
        "Malayalam",
        "Kannada",
        "Odia",
        "Punjabi",
        "Assamese",
        "Maithili",
        "Santali",
        "Konkani",
        "Sindhi",
        "Kashmiri",
        "Nepali",
        "Manipuri",
        "Bodo",
        "Sanskrit",
      ],
      optional: true,
      placeholder: "Select Languages Known",
    },
    {
      name: "foreignLanguagesKnown",
      label: "Foreign Languages Known",
      type: "selectmulti",
      options: [
        "English",
        "Spanish",
        "French",
        "German",
        "Italian",
        "Portuguese",
        "Russian",
        "Chinese (Mandarin)",
        "Japanese",
        "Korean",
        "Arabic",
        "Turkish",
        "Dutch",
        "Swedish",
        "Norwegian",
        "Danish",
        "Greek",
        "Hebrew",
        "Polish",
        "Thai",
        "Vietnamese",
        "Indonesian",
        "Malay",
        "Filipino (Tagalog)",
        "Czech",
        "Hungarian",
        "Ukrainian",
        "Romanian",
        "Bulgarian",
        "Slovak",
        "Croatian",
        "Serbian",
        "Bosnian",
        "Lithuanian",
        "Latvian",
        "Estonian",
        "Swahili",
      ],
      optional: true,
      placeholder: "Enter Foreign Languages Known",
    },
  ],

  //placemnet

  [
    {
      name: "registernumber",
      label: "Registration Number *",
      type: "text",
      optional: false,
      placeholder: "Registration Number",
    },
    {
      name: "internship",
      label: "	Are you interested in Internship? *",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
      placeholder: "",
    },
    {
      name: "placement",
      label: "Are you interested in Placements *",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
      placeholder: "",
    },
    {
      name: "noplacemnetreason",
      label: "If No, Select one of the options below",
      type: "select",
      options: ["Higher Education", "Entrepreneurship"],
      optional: true,
      placeholder: "Select Reason",
    },

    {
      name: "paidtraining",
      label: "	Are you interested in paid trainings for placements? *",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
      placeholder: "",
    },

    {
      name: "gvtjobtraining",
      label: "Are you looking for Government Job Paid Training? *",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
      placeholder: "",
    },

    {
      name: "interestedtraining",
      label: "Which training are you interested in? *",
      type: "radio",
      options: [
        "Self Placed Training",
        "External Vendor / Expert Training",
        "Not Interested",
        "NA",
      ],
      optional: false,
      placeholder: "",
    },
    {
      name: "hoursoftraining",
      label: "How many hours are you ready to commit for Training (Daily)? *",
      type: "select",
      options: ["2 - 3 Hours", "3 - 5 Hours", "5 - 6 Hours", "NA"],
      optional: false,
      placeholder: "Hours Range",
    },
    {
      name: "expectedsalary",
      label: "Expected Salary Range *",
      type: "select",
      options: [
        "Less than 3 LPA",
        "Between 3 LPA to 5 LPA",
        "Above 5 LPA",
        "NA",
      ],
      optional: false,
      placeholder: "Expected Salary Range",
    },
    {
      name: "preferedlocation",
      label: "Preferes Job Location *",
      type: "select",
      options: [
        "Chennai",
        "Madurai",
        "Coimbatore",
        "Trichy",
        "Salem",
        "Erode",
        "Within the State (Tamil Nadu)",
        "Anywhere in India",
        "NA",
      ],
      optional: false,
      placeholder: "Preferes Job Location",
    },

    {
      name: "currentintern",
      label: "Current Internship *",
      type: "text",
      optional: false,
      placeholder: "Current Internship",
    },
    {
      name: "currenttraining",
      label: "Current Training *",
      type: "text",
      optional: false,
      placeholder: "Current Training",
    },
    {
      name: "latestcgpa",
      label: "CGPA upto last Semester *",
      type: "text",
      optional: false,
      placeholder: "CGPA upto last Semester",
    },
    {
      name: "noofstandingarrears",
      label: "No of Current Standing Arrears(Backlogs) *",
      type: "number",
      optional: false,
      placeholder: "No of Current Standing Arrears(Backlogs)",
    },
    {
      name: "parttimejob",
      label: "Are you currently working on part-time job? *",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
      placeholder: "",
    },
    {
      name: "primaryskills",
      label: "Primary Skill Set *",
      type: "selectmulti",
      options: [
        "Python",
        "C",
        "Java",
        "Full Stack Development",
        "Graphics Design",
        "Web Design & Development",
        "Database management (Oracle | SQL | MySql | MongoDB)",
        "Cyber Security (CEH | Penetration Testing)",
        "MERN Stack",
        "Cloud Computing (AWS | Azure | Google Cloud)",
        "Data Analytics (Tableau | Power BI | Google Analytics)",
        "Machine Learning",
        "Mechanical Design (AutoCAD | Solid Works |CREO)",
        "Embedded / VLSI",
        "Matlab / Xilinx / PSpice / Circuit Simulator / Cadence / Ansys DesignSpace /AutoCAD",
        "Medical Coding",
        "Medical Equipments (Sales | Service | Marketing)",
        "Others",
        "NA",
      ],
      optional: false,
      placeholder: "Primary Skill Set",
    },
    {
      name: "primaryskills_others",
      label: "Other Primary Skills *",
      type: "otherinselect",
      depends: "primaryskills",
      optional: false,
      placeholder: "Enter Other Primary Skills ",
    },

    {
      name: "secondaryskills",
      label: "Secondary Skill Set *",
      type: "selectmulti",
      options: [
        "Python",
        "C",
        "Java",
        "Full Stack Development",
        "Graphics Design",
        "Web Design & Development",
        "Database management (Oracle | SQL | MySql | MongoDB)",
        "Cyber Security (CEH | Penetration Testing)",
        "MERN Stack",
        "Cloud Computing (AWS | Azure | Google Cloud)",
        "Data Analytics (Tableau | Power BI | Google Analytics)",
        "Machine Learning",
        "Mechanical Design (AutoCAD | Solid Works |CREO)",
        "Embedded / VLSI",
        "Matlab / Xilinx / PSpice / Circuit Simulator / Cadence / Ansys DesignSpace /AutoCAD",
        "Medical Coding",
        "Medical Equipments (Sales | Service | Marketing)",
        "Others",
        "NA",
      ],
      optional: false,
      placeholder: "Secondary  Skill Set",
    },

    {
      name: "secondaryskills_others",
      label: "Other Secondary Skills *",
      type: "otherinselect",
      depends: "secondaryskills",
      optional: false,
      placeholder: "Enter Other Secondary Skills ",
    },
  ],
  //Hostel
  [
    {
      name: "foodPreference",
      label: "Food Preference *",
      type: "select",
      options: ["Veg", "Non Veg", "Egg"],
      optional: false,
      placeholder: "Select Food Preference",
    },

    {
      name: "hostelStudent",
      label: "Hostel Student *",
      type: "radio",
      options: ["Yes", "No"],
      optional: false,
      placeholder: "Hostel",
    },
    {
      name: "visitorName",
      label: "Visitor Name (Other than Father / Mother)",
      type: "text",
      optional: true,
      placeholder: "Enter Visitor Name",
    },
    {
      name: "visitorRelation",
      label: "Visitor Relation",
      type: "text",
      optional: true,
      placeholder: "Enter Visitor Relation",
    },
    {
      name: "visitorAadhar",
      label: "Visitor Aadhar",
      type: "text",
      optional: true,
      placeholder: "Enter Visitor Aadhar",
    },
    {
      name: "visitorPAN",
      label: "Visitor PAN",
      type: "text",
      optional: true,
      placeholder: "Enter Visitor PAN",
    },
    {
      name: "visitorPhone",
      label: "Visitor Phone",
      type: "phone",
      optional: true,
      placeholder: "Enter Visitor Phone",
    },
    {
      name: "visitorDOB",
      label: "Visitor DOB",
      type: "date",
      optional: true,
      placeholder: "Enter Visitor DOB",
    },
    {
      name: "visitorAddress",
      label: "Visitor Address",
      type: "textarea",
      optional: true,
      placeholder: "Enter Visitor Address",
    },
  ],
];

export const initialFatherValues = [
  // { name: 'fatherId', label: 'Father Id', type: 'text', optional: true, placeholder: 'Enter Father ID' },
  {
    name: "fatherFirstName",
    label: "Father's First Name*",
    type: "text",
    optional: false,
    placeholder: "Enter Father's First Name",
  },
  {
    name: "fatherDateOfBirth",
    label: "Father's Date of Birth (DD/MM/YYYY)*",
    type: "date",
    optional: false,
    placeholder: "Enter Father's Date of Birth",
  },
  {
    name: "fatherEmail",
    label: "Father's E-Mail Address",
    type: "text",
    optional: true,
    placeholder: "Enter Father's Email Address",
  },
  {
    name: "fatherPrimaryMobileNo",
    label: "Father's Primary Mobile No*",
    type: "phone",
    optional: false,
    placeholder: "Enter Father's Primary Mobile No",
  },
  {
    name: "fatherSecondaryMobileNo",
    label: "Father's Secondary Mobile No",
    type: "phone",
    optional: true,
    placeholder: "Enter Father's Secondary Mobile No",
  },
  {
    name: "fatherAddressLine1",
    label: "Father's Address Line 1*",
    type: "textarea",
    optional: false,
    placeholder: "Enter Father's Address Line 1",

    sameaslable: "Student Address",
    populate: true,
    sameas: "address",
  },
  {
    name: "fatherArea",
    label: "Father's Area*",
    type: "text",
    optional: false,
    placeholder: "Enter Father's Area",
    sameaslable: "Student Area",
    populate: true,
    sameas: "area",
  },
  {
    name: "fatherTownVillage",
    label: "Father's Town/Village*",
    type: "text",
    optional: false,
    placeholder: "Enter Father's Town/Village",
    sameaslable: "Student Town/Village",
    populate: true,
    sameas: "townVillage",
  },
  {
    name: "fatherPincode",
    label: "Father's Pincode*",
    type: "text",
    optional: false,
    placeholder: "Enter Father's Pincode",
    sameaslable: "Student Pincode",
    populate: true,
    sameas: "pincode",
  },
  {
    name: "fatherProfession",
    label: "Father's Profession*",
    type: "select",
    options: [
      "Private Employee",
      "Public Sector Employee",
      "Businessman",
      "Self-employed",
      "Farmer",
      "Teacher",
      "Doctor",
      "Lawyer",
      "Government Officer",
      "Military Personnel",
      "Daily wages",
      "Retired",
      "Student",
      "Entrepreneur",
    ],
    optional: false,
    placeholder: "Select Profession",
  },
  {
    name: "fatherIncome",
    label: "Father's Income*",
    type: "select",
    options: ["<2.5L", "2.5L to 5L", "5L to 10L", ">10L"],
    optional: false,
    placeholder: "Select Income Range",
  },
];

export const initialMotherValues = [
  // { name: 'motherId', label: 'Mother Id', type: 'text', optional: true, placeholder: 'Enter Mother ID' },
  {
    name: "motherFirstName",
    label: "Mother's First Name*",
    type: "text",
    optional: false,
    placeholder: "Enter Mother's First Name",
  },
  {
    name: "motherDateOfBirth",
    label: "Mother's Date of Birth (DD/MM/YYYY)*",
    type: "date",
    optional: false,
    placeholder: "Enter Mother's Date of Birth",
  },
  {
    name: "motherEmail",
    label: "Mother's E-Mail Address",
    type: "text",
    optional: true,
    placeholder: "Enter Mother's Email Address",
  },
  {
    name: "motherPrimaryMobileNo",
    label: "Mother's Primary Mobile No*",
    type: "phone",
    optional: false,
    placeholder: "Enter Mother's Primary Mobile No",
  },
  {
    name: "motherSecondaryMobileNo",
    label: "Mother's Secondary Mobile No",
    type: "phone",
    optional: true,
    placeholder: "Enter Mother's Secondary Mobile No",
  },
  {
    name: "motherAddressLine1",
    label: "Mother's Address Line 1*",
    type: "textarea",
    optional: false,
    placeholder: "Enter Mother's Address Line 1",
    sameaslable: "Student Address",
    populate: true,
    sameas: "address",
  },
  {
    name: "motherArea",
    label: "Mother's Area*",
    type: "text",
    optional: false,
    placeholder: "Enter Mother's Area",
    sameaslable: "Student Area",
    populate: true,
    sameas: "area",
  },
  {
    name: "motherTownVillage",
    label: "Mother's Town/Village*",
    type: "text",
    optional: false,
    placeholder: "Enter Mother's Town/Village",
    sameaslable: "Student Town/Village",
    populate: true,
    sameas: "townVillage",
  },
  {
    name: "motherPincode",
    label: "Mother's Pincode*",
    type: "text",
    optional: false,
    placeholder: "Enter Mother's Pincode",
    sameaslable: "Student Pincode",
    populate: true,
    sameas: "pincode",
  },
  {
    name: "motherProfession",
    label: "Mother's Profession*",
    type: "select",
    options: [
      "Housewife",
      "Private Employee",
      "Public Sector Employee",
      "Businessman",
      "Self-employed",
      "Farmer",
      "Teacher",
      "Doctor",
      "Lawyer",
      "Government Officer",
      "Military Personnel",
      "Daily wages",
      "Retired",
      "Student",
      "Entrepreneur",
    ],
    optional: false,
    placeholder: "Select Profession",
  },
  {
    name: "motherIncome",
    label: "Mother's Income*",
    type: "select",
    options: ["<2.5L", "2.5L to 5L", "5L to 10L", ">10L"],
    optional: false,
    placeholder: "Enter Mother's Income",
  },
];

export const initialGuardianValues = [
  // { name: 'guardianId', label: 'Guardian Id', type: 'text', optional: true, placeholder: 'Enter Guardian ID' },
  {
    name: "guardianFirstName",
    label: "Guardian's First Name*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's First Name",
  },
  {
    name: "guardianGender",
    label: "Guardian's Gender*",
    type: "select",
    options: ["Male", "Female", "Other"],
    optional: false,
    placeholder: "Select Gender",
  },
  {
    name: "guardianDateOfBirth",
    label: "Guardian's Date of Birth (DD/MM/YYYY)*",
    type: "date",
    optional: false,
    placeholder: "Enter Guardian's Date of Birth",
  },
  {
    name: "guardianEmail",
    label: "Guardian's E-Mail Address",
    type: "text",
    optional: true,
    placeholder: "Enter Guardian's Email Address",
  },
  {
    name: "guardianPrimaryMobileNo",
    label: "Guardian's Primary Mobile No*",
    type: "phone",
    optional: false,
    placeholder: "Enter Guardian's Primary Mobile No",
  },
  {
    name: "guardianSecondaryMobileNo",
    label: "Guardian's Secondary Mobile No",
    type: "phone",
    optional: true,
    placeholder: "Enter Guardian's Secondary Mobile No",
  },
  {
    name: "guardianAddressLine1",
    label: "Guardian's Address Line 1*",
    type: "textarea",
    optional: false,
    placeholder: "Enter Guardian's Address Line 1",
  },
  {
    name: "guardianArea",
    label: "Guardian's Area*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's Area",
  },
  {
    name: "guardianTownVillage",
    label: "Guardian's Town/Village*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's Town/Village",
  },
  {
    name: "guardianPincode",
    label: "Guardian's Pincode*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's Pincode",
  },
  {
    name: "guardianRelationWithStudent",
    label: "Guardian's Relation with Student*",
    type: "text",
    optional: false,
    placeholder: "Enter Guardian's Relation with Student",
  },
  {
    name: "guardianProfession",
    label: "Guardian's Profession*",
    type: "select",
    options: [
      "Private Employee",
      "Public Sector Employee",
      "Businessman",
      "Self-employed",
      "Farmer",
      "Teacher",
      "Doctor",
      "Lawyer",
      "Daily wages",
      "Government Officer",
      "Military Personnel",
      "Housewife",
      "Retired",
      "Student",
      "Entrepreneur",
    ],
    optional: false,
    placeholder: "Select Profession",
  },
  {
    name: "guardianIncome",
    label: "Guardian's Income*",
    type: "select",
    options: ["<2.5L", "2.5L to 5L", "5L to 10L", ">10L"],
    optional: false,
    placeholder: "Enter Guardian's Income",
  },
];

export const stepNames = [
  "Search Details",
  "Basic Details",
  "Personal Details",
  "School Details",
  "Identity Details",
  "Placement Details",
  "Hostel Deatils",
];
